### PR TITLE
Export function and digitization docs

### LINKED ISSUE #92: Write an Export function that saves data from ChannelWorm to PyOpenWorm
This will be a facade that calls the adapter classes going from CW to PyOW.

### LINKED ISSUE #98: Add digitization best practices to the walkthrough
Plots like those digitized by @rayner in openworm/muscle_model#40 do not have original data points, nor zeroed axes. 
The current walkthrough does not address this possibility, so the practices employed by @rayner should be included there as well.

### LINKED ISSUE #158: Document how to plot multiple series on one plot
It's not clear to me how to plot two or more series for a single plot, such as this [one](http://channelwormdjango-channelworm.rhcloud.com/media/ion_channel/graph/2015/08/09/Screen_Shot_2015-08-09_at_10.01.35_AM.png)

This was raised by @stripathy at the hackathon.

@VahidGh @miladjafary Any tips?

Also, we should document this for future use.

### PR DESCRIPTION
**Pull request by travs**
Fixes #158 
Fixes #98 
Fixes #92

### CODE REVIEW

**Comment by travs** [comment]
This has some commits from #157, so we can merge that one first (when I get the build to pass).

**Comment by travs** [comment]
@VahidGh @miladjafary I'd like to help work the Exporter into an `export` button now. 
Please merge this if all looks good and makes sense

**Comment by VahidGh** [comment]
@travs, looks great :+1:

**Comment by travs** [comment]
Dang, didn't mean to make this pr to master. I'll sync up `dev` now

**Pull request merged**
