### PR TITLE
fix string denotation in channel worm

### PR DESCRIPTION
**Pull request by russelljjarvis**
Hi there is some strange string notation that uses ` ` to signify what I assume is a string data type. Anyway I think I have fixed it.

### CODE REVIEW

**Comment by slarson** [comment]
Looks great.  Thank you!

**Comment by VahidGh** [comment]
When using "`" character in `models`, we tell the Django to read the default string given to a foreign key in a table. 
I'm not sure if a double-quote is doing the same thing here!

**Comment by russelljjarvis** [comment]
Okay thats in fair enough. I was responding to an error message caused by the back ticks in python3, and without Django fully configured. Maybe the issue is caused by python2.7/3 differences or my partial/unconfigured installation of the Django module.

**Comment by rgerkin** [comment]
Yep, backticks were removed in Python 3.  You can use repr() instead.  2to3 will take care of this as well.

**Pull request merged**
